config/routes.rb
Autoshop::Application.routes.draw do
  
  post '/purchases/:id' => 'purchases#create'
  resources :purchases 

  devise_for :users
  resources :cars do
    member do 
      resources :galleries
    end

    collection do
      get 'search'
      post :search
    end
 end
  root to: 'main#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

	belongs_to :user
	has_many :galleries
	belongs_to :purchase
	scope :filtr_brand, -> (brand) {where('brand like ?', brand)}
	scope :price, ->(min,max) {where("price >= ? AND price <= ?", min, max)}
	scope :filtr_model, ->(model) {where('model like ?', model)}


	has_attached_file :photo, {:styles=>{:thumb => "200x150#",:ico=>"50x30#"}, 
		:url => "/system/:style/:hash.:extension",
		:hash_secret => "photo",
		:hash_data => ":class/:attachment/:id/:style/:created_at" 
	
	}
	self.inheritance_column = nil
	validates_attachment_content_type :photo, :content_type=>/\Aimage\/.*\z/

	

	def self.filter(*args)
		
	end

	#scope :cost ->(price_min,price_max){where(:price<=price_max, :price>=price_min )}
	#scope :eng ->(min, max){where(:engine<=max, :engine>=min )}
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
	belongs_to :car
	#validations
	#validates 	:car , presence: true
	# Photo uploader using carrierwave
    #has_many :imgs, as:im
    has_attached_file :img, {:styles=>{:thumb => "200x150#",:ico=>"50x30#"}, 
		:url => "/system/:style/:hash.:extension",
		:hash_secret => "img",
		:hash_data => ":class/:attachment/:id/:style/:created_at" 
	}

	
	validates_attachment_content_type :img, :content_type=>/\Aimage\/.*\z/
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
	has_many :cars
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :cars
  has_many :purchases

  def purchased_car?(car,user)
  	!user.purchases.where(car_id: car).empty?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_filter :configure_permitted_parameters, if: :devise_controller?
    protect_from_forgery with: :exception
    protected
    def configure_permitted_parameters
   		devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :second_name, :adress, :postcode, :post, :phone, :born, :password, :password_confirmation, :email) }
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  def showsearch

  end
  # GET /cars/1
  # GET /cars/1.json
  def show
    @galleries = Gallery.all.where(car_id: params[:id])
    @user = current_user
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def search
    if (params[:car].present?) 
      @cars = Car.filtr_brand(params[:car][:brand]) unless params[:car][:brand].empty?                            
      @cars = @cars.filtr_model(params[:car][:model]) unless params[:car][:model].empty? 
      @cars= @cars.price(params[:car][:min], params[:car][:max])  unless (params[:car][:min].empty? or params[:car][:max].empty? )                        
      
    end    
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.user_id = current_user.id
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to new_gallery_path(@car), notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:brand,  :model, :engine,  :year,  :milage,  :gearcase,  :type,  :fuel,  :doors,  :stan,  :broken,  :color,  :power, :description, :info, :equipment, :price, :photo)      
    end
    
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	def index
		@galleries = Gallery.all.where(car_id: params[:id])
	end

	def new
		@galleries = Gallery.new
	end

	def show
		@galleries = Gallery.find(params[:id])
 	end	

	def create
		gallery_params.each{|img| 
			gallery_for_car=Gallery.new(img: img, car_id: params[:id])
			gallery_for_car.save
		}
		  redirect_to galleries_path(params[:id])
	end


	private
		def gallery_params
			params[:gallery][:img]
		end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_purchase, only: [:show, :edit, :update, :destroy]

  # GET /purchases
  # GET /purchases.json
  def index
    @purchases = Purchase.all
  end

  # GET /purchases/1
  # GET /purchases/1.json
  def show
  end

  # GET /purchases/new
  def new
    @purchase = Purchase.new
  end

  # GET /purchases/1/edit
  def edit
  end

  # POST /purchases
  # POST /purchases.json
  def create
    @purchase = Purchase.new(car_id: params[:id], user: current_user )
    respond_to do |format|
      if @purchase.save
        format.html { redirect_to @purchase, notice: 'Purchase was successfully created.' }
        format.json { render action: 'show', status: :created, location: @purchase }
        
      else
        format.html { render action: 'new' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchases/1
  # PATCH/PUT /purchases/1.json
  def update
    respond_to do |format|
      if @purchase.update(purchase_params)
        format.html { redirect_to @purchase, notice: 'Purchase was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @purchase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchases/1
  # DELETE /purchases/1.json
  def destroy
    @purchase.destroy
    respond_to do |format|
      format.html { redirect_to purchases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase
      @purchase = Purchase.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_params
      params[:purchase]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
 
    <% @cars.each do |car| %>
            <div class=".col1" style="float:left; padding:20px;">
              <%= image_tag car.photo.url(:thumb), class: 'thumbnail' %>
              
                <ul style="list-style: none;" >
                 <li><%= car.brand %> <%= car.model %> </li>
                 <li>Pojemność silnika(cm3): <%= car.engine %> </li>
                 <li>Paliwo: <%= car.fuel %> </li>
                 <li>Liczba drzwi: <%= car.doors %> </li>
                 <li>Skrzynia biegów: <%= car.gearcase %> </li>
                  <li>Przebieg: <%= car.milage %></li>
                  <li>Kolor: <%= car.color %>  </li>
                  <li>Typ pojazdu: <%= car.type %>  </li>
                  <li>Stan: <%= car.stan %> </li>
                  <li>Moc silnika (KM): <%= car.engine %>  </li>
                  <li>Rok produkcji: <%= car.year %> </li>
              </ul>
            
           
           <%= link_to 'Show', car, class: "btn btn-default" %>
          <%if user_signed_in? %>
           <% if current_user.id == car.user_id %>
           <%= link_to 'Edit', edit_car_path(car), class: "btn btn-default"  %>
           <%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-default" %>
           <% end %>
          <% end %>
           </div>
    <% end %>
    
  <%if user_signed_in? %>
           <%= link_to 'New Car', new_car_path, class: "btn btn-default" %>
  <% end %>

app/views/cars/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Tworzenie oferty samochodu
  </div>
  <div class="panel-footer">
	<%= simple_form_for @car, :html => {:multipart => true} do |f| %>
	  
 <%= f.input :brand,collection: ['Audi','BMW','Citroen','Daewoo','Fiat','Ford','Honda','Mazda', 'Mercedes-benz',
    'Opel','Peugeot','Renault','Seat','Skoda','Toyota','Volkswagen'] , label: 'Marka Samochodu:',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' } %>



    
   <%= f.input :model, label:'Wprowadz model samochodu' ,:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
   


      <%= f.input :year, collection: 1960..2014, label: 'Rok produkcji:',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label'}  %>
      <%= f.input :milage, label: 'Przebieg:', :input_html => { class: 'form-control' } ,:label_html => { class: 'control-label' }  %>
      <%= f.input :gearcase, collection: ['Automat','Manualna'], label: 'Skrzynia biegów:',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :type, collection: ['Hatchback','Sedan/Limuzyna','Kombi','Van'], label: 'Typ:',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :engine, label: 'Silnik (cm3):', :input_html => { class: 'form-control' } ,:label_html => { class: 'control-label' }  %>
      <%= f.input :fuel, collection: ['Benzyna','Diesel','Benzyna + LPG'], label: 'Rodzaj paliwa',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :doors, collection: 3..5, label: 'Drzwi', class: 'form-control',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :stan, collection: ['Nowy','Używany'], label: 'Stan Samochodu', :input_html => { class: 'form-control' } ,:label_html => { class: 'control-label' }  %>
      <%= f.input :broken,collection: [:true, :false], label: 'Uszkodzony',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :color, label: 'Kolor',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :power, label: 'Moc silnika (KM)',:input_html => { class: 'form-control' } , :label_html => { class: 'control-label' }  %>
      <%= f.input :description, as: :text, label: 'Opis', input_html: {class: 'form-control', rows: '5' } , :label_html => { class: 'control-label' } %>
      <%= f.input :equipment, as: :text, label: 'Wyposarzenie', input_html: {class: 'form-control', rows: '5'} , :label_html => { class: 'control-label' } %>
      <%= f.input :info, as: :text, label: 'Dodatkowe informacje', input_html: {class: 'form-control', rows: '5'}, :label_html => { class: 'control-label' }  %>
      <%= f.input :price, label: 'Cena', :label_html => { class: 'control-label' }  %>
      <%= f.input :photo, as: :file, label: 'Dodaj avatar', :label_html => { class: 'control-label' }   %><br />
      <%= f.button :submit, 'Dodaj', class: 'btn btn-primary' %>
	<% end %>
  </div>
</div>

<%= link_to 'Back', cars_path,  class: 'btn btn-default' %>

app/views/cars/search.html.erb
 <%= simple_form_for 'car', class: "form-inline" do |f| %>
  
    <%= f.input :brand, label: 'Marka', class: "form-control" %><br />
    <%= f.input :model, label: 'Model', class: "form-control" %><br />
    
    <%= f.input :min, label: 'min', class: "form-control" %><br />
    <%= f.input :max, label: 'max', class: "form-control" %><br />
    
    <%= f.submit "Search", class: "btn btn-primary" %>
  
 <% end %>

 <% if @cars %>

  <% @cars.each do |car| %>
            <div class=".col1" style="float:left;">
              <%= image_tag car.photo.url(:thumb), class: 'thumbnail' %>
              <h4 class="media-heading"></h4> 
                <ul >
                 <li><%= car.brand %> <%= car.model %> </li>
                 <li>Pojemność silnika(cm3): <%= car.engine %> </li>
                 <li>Paliwo: <%= car.fuel %> </li>
                 <li>Liczba drzwi: <%= car.doors %> </li>
                 <li>Skrzynia biegów: <%= car.gearcase %> </li>
                  <li>Przebieg: <%= car.milage %></li>
                </ul>
  
                <ul>
                  <li>Kolor: <%= car.color %>  </li>
                  <li>Typ pojazdu: <%= car.type %>  </li>
                  <li>Stan: <%= car.stan %> </li>
                  <li>Moc silnika (KM): <%= car.engine %>  </li>
                  <li>Rok produkcji: <%= car.year %> </li>
              </ul>
            
           
           <%= link_to 'Show', car, class: "btn btn-default" %>
           
           </div>
    <% end %>

 <% end %>













 

app/views/cars/show.html.erb
<div class="container">
	<h2><%= @car.brand %> <%= @car.model %></h2>
	 <ul style="list-style: none;">
       <li>Pojemność silnika(cm3): <%= @car.engine %> </li>
       <li>Paliwo: <%= @car.fuel %> </li>
       <li>Liczba drzwi: <%= @car.doors %> </li>
       <li>Skrzynia biegów: <%= @car.gearcase %> </li>
       <li>Przebieg: <%= @car.milage %></li>
       <li>Kolor: <%= @car.color %>  </li>
       <li>Typ pojazdu: <%= @car.type %>  </li>
       <li>Stan: <%= @car.stan %> </li>
       <li>Moc silnika (KM): <%= @car.engine %>  </li>
       <li>Opis: <%= @car.description %> </li>
       <li>Wyposarzenie: <%= @car.equipment %> </li>
       <li>Dodatkowe informacje: <%= @car.info %> </li>
      <li>Cena: <%= @car.price %> </li>
     </ul>
     <div class="panel panel-primary">
      <div class="panel-heading">
        Galeria zdjęć samochodu
        </div>
        <div class="panel-body">
            <div class="row">
             <% @galleries.each do |g| %>
             <div class="col-xs-6 col-md-3">
                <%= image_tag g.img.url(:thumb), class: "thumbnail" %>
             </div>
            <% end %>
            </div>
        </div>
     </div>
</div>
<%= link_to 'Back', cars_path, class: "btn btn-primary"  %> 
<%if user_signed_in? %>
  <% if current_user.id == @car.user_id %>
    <%= link_to 'Edit', edit_car_path(@car), class: "btn btn-primary" %> 
    <%= link_to 'Dodaj zdjecia', new_gallery_path(@car), class: "btn btn-primary"  %>
  
  <% if !@user.purchased_car?(@car,@user) %>
    <% unless (current_user.id == @car.user_id) %>
      <%= link_to 'Zamow', purchase_path(@car),method: :post, data: { confirm: 'Are you sure?' } ,class: "btn btn-primary"  %>
    <% end %> 
  <% end %>
<% end %>
<% end %>
 

app/views/galleries/index.html.erb
 
<div class="row">
   
 <% @galleries.each do |g| %>
  <div class="col-xs-6 col-md-3">
   <%= image_tag g.img.url(:thumb), class: "thumbnail" %>
   </div>
 <% end %>
 </div>

app/views/galleries/new.html.erb
<h2> Dodawanie zjdec do galeri</h2>

<%= simple_form_for @galleries , :html => {:multipart => true} do |f| %>
	<%= f.input :img, input_html: { multiple: 'multiple' }, as: :file ,label: 'Dodaj zdjecia', :label_html => { class: 'control-label' } %>
	<%= f.submit 'Dodaj zdecia', class: 'btn btn-primary' %>
<% end %>

app/views/galleries/show.html.erb
 <%= image_tag @galleries.img.url(:thumb) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Autoshop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div><%= link_to "AutoShop", root_path, :class=>"navbar-brand" %></div>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
             <li><%= link_to "Samochody", cars_path, :class=>"active" %></li></li>
            <li><%= link_to "Szukaj", search_cars_path, :class=>"active" %></li></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
              <%if !user_signed_in? %>
                <%= link_to "Zaloguj się", new_user_session_path, :class=>"active" %>
              <% end %>
              </li>
              <%if !user_signed_in? %>
              <li>
                <%= link_to "Zarejestruj się", new_user_registration_path, :class=>"active" %>
              </li>
              <% else %>
              <li class="active">
                 <%= link_to current_user.first_name, user_session_path , class:"active" %>
              </li>
              <li>
                <%= link_to "Wyloguj", destroy_user_session_path, :method => :delete, class:'active' %>
              </li>  
             <% end %>                                            
          </ul>
        </div><!--/.nav-collapse -->
      </div>

    </div>


	<div class="container">
		<div class="okno">
			<%= yield %>
		</div>
	</div>

    <div class="container">
     <hr />
     <div class="footer">
      copyright
    </div>
</body>
</html>

app/views/main/index.html.erb
<div class="container">
	<div class="cols1">
		<h3>Witaj na stronie Autoshop</h3>
		<p>
			Znajdziesz tu ciekawe oferty samochodów osobowych. 
		</p>
	</div>
	<div class="cols2">
		<%if !user_signed_in? %>
			<div class="panel panel-default">
				<div class="panel-heading"> Zaloguj się</div>
 				<div class="panel-body">
   					Aby skorzystać ze wszystkich usług:<br />
   					<%= link_to 'Zaloguj się ', new_user_session_path, class: "btn btn-default" %><br />
   					<br />
   					Jeśli nie masz jeszcze konta<br/>
   					<%= link_to 'Zarejestruj się ',  new_user_registration_path, class: "btn btn-default" %>
  				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/purchases/_form.html.erb
<%= simple_form_for(@purchase) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/purchases/edit.html.erb
<h1>Editing purchase</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase %> |
<%= link_to 'Back', purchases_path %>

app/views/purchases/index.html.erb
<h1>Listing purchases</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @purchases.each do |purchase| %>
      <tr>
        <td><%= link_to 'Show', purchase %></td>
        <td><%= link_to 'Edit', edit_purchase_path(purchase) %></td>
        <td><%= link_to 'Destroy', purchase, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase', new_purchase_path %>

app/views/purchases/new.html.erb
<h1>New purchase</h1>

<%= render 'form' %>

<%= link_to 'Back', purchases_path %>

app/views/purchases/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_purchase_path(@purchase) %> |
<%= link_to 'Back', purchases_path %>